# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/mi-lambda-funcion.zip'
    replaceExistingArchive: true

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'ConexionAws'
    regionName: 'us-east-1'
    deploymentMode: 'codeonly'
    functionName: 'funsion-prueba-lambda'
    codeLocation: 'localfile'
    localZipFile: '$(Build.ArtifactStagingDirectory)/mi-lambda-funcion.zip'